Update README.md
thoth-station/ttm-as-a-service pull request #32
Opened 2022-12-01 16:17 UTC by Gkrumbach07

## Related Issues and Dependencies

## This introduces a breaking change

- Yes
- No

## This should yield a new module release

- Yes
- No

## This Pull Request implements

### Description

Updated readme

2022-12-01 16:17 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from gkrumbach07 by writing `/assign @gkrumbach07` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fttm-as-a-service).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/ttm-as-a-service/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["gkrumbach07"]} -->

2022-12-01 16:17 UTC, sesheta commented
@Gkrumbach07: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 7a079558e44c0df64813bb9e266a3aa7df026942 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/thoth-station_ttm-as-a-service/32/pre-commit/1598350552347971584) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=ttm-as-a-service&pr=32). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGkrumbach07). Please help us and [open an issue](https://github.com/thoth-station/ttm-as-a-service/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-12-01 16:19 UTC, harshad16 requested changes
can have one change

2022-12-01 16:19 UTC, harshad16 commented on README.md
> +Project is being archived. Read comment [here](https://github.com/thoth-station/core/issues/425#issuecomment-1334012921) for more info on how to use this app.
It would be great if we copy the details here instead of pointing to the issue.

2022-12-01 16:19 UTC, Gkrumbach07 commented on README.md
> +Project is being archived. Read comment [here](https://github.com/thoth-station/core/issues/425#issuecomment-1334012921) for more info on how to use this app.
will do. also pre-commit is old and failing in this repo

2022-12-01 16:20 UTC, harshad16 commented on README.md
> +Project is being archived. Read comment [here](https://github.com/thoth-station/core/issues/425#issuecomment-1334012921) for more info on how to use this app.
change this to https://github.com/thoth-station/ttm-as-a-service/blob/b62caca5e075bb19b2326b16a7bed9110fd3f5b6/.pre-commit-config.yaml#L37
github url inplace of gitlab

2022-12-01 16:20 UTC, sesheta commented
@Gkrumbach07: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | f5a4b94a75d277cffe83495b15713dd3cd059195 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/thoth-station_ttm-as-a-service/32/pre-commit/1598351370644099072) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=ttm-as-a-service&pr=32). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGkrumbach07). Please help us and [open an issue](https://github.com/thoth-station/ttm-as-a-service/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-12-01 18:12 UTC, Gkrumbach07 commented
/approve

2022-12-01 18:12 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/ttm-as-a-service/pull/32#issuecomment-1334161701" title="Approved">Gkrumbach07</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fttm-as-a-service).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/ttm-as-a-service/blob/main/OWNERS)~~ [Gkrumbach07]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-01 18:13 UTC, harshad16 reviewed
one additional comment

2022-12-01 18:13 UTC, harshad16 commented on README.md
> +TTM project is being archived. Latest information on TTM related projects can be found over here:  https://github.com/redhat-et/time-to-merge-tool
```suggestion
TTM Github App project will not be actively pursued and is being archived. User can use this project going forward if they like to or other option like TTM GitHub action is being implemented and available with the latest information on TTM-related projects can be found over here:  https://github.com/redhat-et/time-to-merge-tool
```

2022-12-02 17:23 UTC, harshad16 reviewed
/lgtm

thanks :+1:

2022-12-02 17:25 UTC, merged